deployment:
  tasks:
    - /usr/local/cpanel/3rdparty/bin/git checkout --force
    - /usr/local/cpanel/3rdparty/bin/npm install
    - /usr/local/cpanel/3rdparty/bin/npm run build
    - /bin/cp -R build/* /home/vwdlqzcdetoz/public_html/pereirabot.com/